### ISSUE TITLE
Adding a field to a shape that already has a field replaces the original field

### ISSUE THREAD

**Issue by gregvonkuster** [pletzer/icqsol#31] opened 2015-09-30 16:06 UTC
The behavior should be to add a 2nd field to the shape, allowing for multiple fields per shape.

**Comment by pletzer** [comment] 2015-09-30 16:43
I agree. I think the problem is simply that I'm copying the vertices and
polygons into the new poly data but not the existing fields. Yes to
incrementally adding fields, no to adding multiple colors -- there can only
be one color.

--Alex

On Wed, Sep 30, 2015 at 12:06 PM, Greg Von Kuster <notifications@github.com>
wrote:

> The behavior should be to add a 2nd field to the shape, allowing for
> multiple fields per shape.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pletzer/icqsol/issues/31>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by pletzer** [comment] 2015-11-20 17:50
I think the problem is that icqRefineSurface does not interpolate the existing field onto the new grid. The solution would be to use set_attributes in the triangulation call and load the field data when buildng the vtkPolyData object.

**Comment by pletzer** [comment] 2015-11-24 04:23
Point and cell data are now carried over when refining the mesh. This allows one to add as many fields as one wishes.

**Comment by gregvonkuster** [comment] 2015-11-28 14:51
@pletzer I don't see this working, at least with our icqsol Galaxy tools.  I'm running the latest code from the icqsol package.  If I create this dataset using the icqsol_create_shape tool:

# vtk DataFile Version 3.0
vtk output
ASCII
DATASET POLYDATA
POINTS 24 float
0 0 0 0 0 1 0 1 1 
0 1 0 1 0 0 1 1 0 
1 1 1 1 0 1 0 0 0 
0 0 0 0 0 1 0 0 1 
0 1 1 0 1 1 0 1 0 
0 1 0 1 0 0 1 0 0 
1 1 0 1 1 0 1 1 1 
1 1 1 1 0 1 1 0 1 

POLYGONS 6 30
4 0 1 2 3 
4 4 5 6 7 
4 8 16 22 10 
4 14 12 20 18 
4 9 15 19 17 
4 11 23 21 13 

POINT_DATA 24
NORMALS Normals float
-1 0 0 -1 0 0 -1 0 0 
-1 0 0 1 0 0 1 0 0 
1 0 0 1 0 0 0 -1 0 
0 0 -1 0 -1 0 0 0 1 
0 1 0 0 0 1 0 1 0 
0 0 -1 0 -1 0 0 0 -1 
0 1 0 0 0 -1 0 1 0 
0 0 1 0 -1 0 0 0 1

I then add a surface field named "surface_field" to the shape using the icqsol_add_surface_field_from_expression tool, producing this dataset:

# vtk DataFile Version 3.0
vtk output
ASCII
DATASET POLYDATA
POINTS 24 float
0 0 0 0 0 1 0 1 1 
0 1 0 1 0 0 1 1 0 
1 1 1 1 0 1 0 0 0 
0 0 0 0 0 1 0 0 1 
0 1 1 0 1 1 0 1 0 
0 1 0 1 0 0 1 0 0 
1 1 0 1 1 0 1 1 1 
1 1 1 1 0 1 1 0 1 

POLYGONS 12 48
3 3 0 1 
3 1 2 3 
3 7 4 5 
3 5 6 7 
3 10 8 16 
3 16 22 10 
3 18 14 12 
3 12 20 18 
3 17 9 15 
3 15 19 17 
3 13 11 23 
3 23 21 13 

CELL_DATA 12
FIELD FieldData 1
surface_field 1 12 double
0.0123457 0.197531 0.878371 1.06356 0.0123457 0.197531 0.0123457 0.197531 0.096225 
0.3849 1.09623 1.3849 
POINT_DATA 24
NORMALS Normals float
-1 0 0 -1 0 0 -1 0 0 
-1 0 0 1 0 0 1 0 0 
1 0 0 1 0 0 0 -1 0 
0 0 -1 0 -1 0 0 0 1 
0 1 0 0 0 1 0 1 0 
0 0 -1 0 -1 0 0 0 -1 
0 1 0 0 0 -1 0 1 0 
0 0 1 0 -1 0 0 0 1 

I then add a surface field named "surface_field1" to the above dataset using the icqsol_add_surface_field_from_expression tool, producing this dataset.  Notice that the dataset does not include 2 surface fields, but just the last one added.

# vtk DataFile Version 3.0
vtk output
ASCII
DATASET POLYDATA
POINTS 24 float
0 1 0 0 0 0 0 0 1 
0 1 1 1 0 1 1 0 0 
1 1 0 1 1 1 0 1 0 
0 1 0 0 0 0 0 0 0 
0 0 1 0 0 1 0 1 1 
0 1 1 1 0 1 1 0 1 
1 0 0 1 0 0 1 1 0 
1 1 0 1 1 1 1 1 1 

POLYGONS 12 48
3 0 1 2 
3 2 3 0 
3 4 5 6 
3 6 7 4 
3 12 10 18 
3 18 16 12 
3 20 8 14 
3 14 22 20 
3 19 11 9 
3 9 21 19 
3 15 13 17 
3 17 23 15 

CELL_DATA 12
FIELD FieldData 1
surface_field1 1 12 double
0.0335582 0.53346 2.09226 2.37602 0.0335582 0.53346 0.0335582 0.53346 0.261163 
1.02062 2.41788 2.67145 
POINT_DATA 24
NORMALS Normals float
-1 0 0 -1 0 0 -1 0 0 
-1 0 0 1 0 0 1 0 0 
1 0 0 1 0 0 0 1 0 
0 0 -1 0 -1 0 0 0 -1 
0 -1 0 0 0 1 0 1 0 
0 0 1 0 -1 0 0 0 1 
0 -1 0 0 0 -1 0 1 0 
0 0 -1 0 1 0 0 0 1

**Comment by pletzer** [comment] 2015-11-28 20:27
@gregvonkuster Test testAddSurfaceFieldFromExpressionBolt3 adds a third field to the input file. At least things seem to work on icqsol side.

**Comment by pletzer** [comment] 2015-11-28 20:31
@gregvonkuster I confirm that adding fields does not work in galaxy.

**Comment by pletzer** [comment] 2015-11-28 20:43
@gregvonkuster Now fixed in galaxy-csg. I added the cell fields and one point field and got:

# vtk DataFile Version 4.0
vtk output
ASCII
DATASET POLYDATA
POINTS 24 float
10 0 0 10 0 1 10 1 1 
10 1 0 11 0 0 11 1 0 
11 1 1 11 0 1 10 0 0 
10 0 0 10 0 1 10 0 1 
10 1 1 10 1 1 10 1 0 
10 1 0 11 0 0 11 0 0 
11 1 0 11 1 0 11 1 1 
11 1 1 11 0 1 11 0 1 

POLYGONS 12 48
3 3 0 1 
3 1 2 3 
3 7 4 5 
3 5 6 7 
3 10 8 16 
3 16 22 10 
3 18 14 12 
3 12 20 18 
3 17 9 15 
3 15 19 17 
3 13 11 23 
3 23 21 13 

CELL_DATA 12
FIELD FieldData 2
surface_field 1 12 double
86.6149 86.8001 104.801 104.987 0.0123457 0.197531 0.0123457 0.197531 92.4723 
98.5344 93.4723 99.5344 
surface_field2 1 12 double
86.6149 86.8001 104.801 104.987 0.0123457 0.197531 0.0123457 0.197531 92.4723 
98.5344 93.4723 99.5344 
POINT_DATA 24
NORMALS Normals float
-1 0 0 -1 0 0 -1 0 0 
-1 0 0 1 0 0 1 0 0 
1 0 0 1 0 0 0 -1 0 
0 0 -1 0 -1 0 0 0 1 
0 1 0 0 0 1 0 1 0 
0 0 -1 0 -1 0 0 0 -1 
0 1 0 0 0 -1 0 1 0 
0 0 1 0 -1 0 0 0 1 

FIELD FieldData 1
surface_field3 1 24 double
0 1 1 1.22465e-14 0 1.48182e-14 1 1 0 
0 1 1 1 1 1.22465e-14 1.22465e-14 0 0 
1.48182e-14 1.48182e-14 1 1 1 1

**Closed by pletzer** 2015-11-28 20:43 UTC
